live: "tcp://127.0.0.1:6668"
info: "tcp://127.0.0.1:8666"
irc:
    - host     : irc.freenode.net
      post     : 6667
      channels :
        - lurkr
        - name:    something_unrelated
          channel: '#lurkr2'
